### ISSUE TITLE
Upgrade to Guzzle 7

### ISSUE THREAD

**Issue by cihantas** [printu/customerio#25]
Many framework and other libraries have upgraded to Guzzle 7. This library would cause problems because of the version conflict and it would be great if we could upgrade it to 7.0 as well. 

The breaking changes are pretty small and are listed here: https://github.com/guzzle/guzzle/blob/7.0.0/UPGRADING.md#60-to-70

**Comment by krzaczek** [comment]
@cihantas should be easy to implement over weekend :)

**Comment by mackmcconnell** [comment]
Glad I found this, we also desperately need this to be on Guzzle 7 or we can’t upgrade our framework. Any update on this?

**Comment by cihantas** [comment]
Edit: My mistake. Looks like it's solved. Thank you so much!

**Comment by krzaczek** [comment]
@cihantas I didn't have enough time to test it so i'm gonna tag a `3.0.0-rc.1` version for now and do some more testing / code quality tommorow

**Comment by cihantas** [comment]
Alright @krzaczek. This should give us some time to upgrade our dependencies. Again, your work is much appreciated.

**Comment by cihantas** [comment]
Is 3.0.0 ready to be considered stable or still RC?

**Comment by krzaczek** [comment]
@cihantas Sorry for the delay .. busy "year" :) There seems to be a change in the customer.io API as of 1 day at least things stopped working for me yesterday on the track.customer.io API. I do have a fix that helps so i'll release a rc.2 today and will do some more testing. Hope to release a stable 3.0 by the end of the week.

**Comment by cihantas** [comment]
Awesome! No worries. Looking forward to it.
