### ISSUE TITLE
Add support for various json decoding modes to the handleRequest method.

### ISSUE THREAD

**Issue by burstmeman-old** [printu/customerio#26]
Hello!
First of all, thanks for the great integration with Customer.io
I want to ask you to add support for different assoc modes to the handleRequest method.

I see it like this

```php
<?php

class Client
{
    /** @var bool Assoc response mode */
    protected $assocMode;

   public function __construct(string $apiKey, string $siteId)
    {
        // ...

        $this->assocMode = false;
    }

    /**
     * Set Assoc mode to response
     * @param bool $mode
     */
    public function setAssocResponseMode(bool $mode)
    {
        $this->assocMode = $mode;
    }

    /**
     * @param ResponseInterface $response
     * @return mixed
     */
    private function handleResponse(ResponseInterface $response)
    {
        $stream = stream_for($response->getBody());

        return json_decode($stream->getContents(), $this->assocMode);
    }

}

**Comment by krzaczek** [comment]
@burstmeman well it's not so simple as all methods depending on handleResponse are assuming ResponseInterface will be returned as result. And adding a flag like this would return ResponseInterface or array.

A better way would probably be adding a global callback function or a middleware to parse the response before returning result from all functions.

**Comment by krzaczek** [comment]
@burstmeman i'll have a look at it.

**Comment by burstmeman-old** [comment]
@krzaczek Can you please tell me if it is worth waiting for this update in the near future or does it make sense to fork the repository?

**Comment by krzaczek** [comment]
@burstmeman feel free to send a MR. I'm a little busy at the moment and don't know when i'll have time to look at it. But if You submit a MR i'll look at it. Please just make it a non-breaking change - so that the default behavior stays the same as now.

**Comment by krzaczek** [comment]
@burstmeman sorry for the delay. I'll check the PR today and will make a new release

**Comment by burstmeman** [comment]
@krzaczek any updates about PR?

**Comment by krzaczek** [comment]
@burstmeman sorry for the delay / this will be merged and released in abount 30 min

**Comment by krzaczek** [comment]
Released in https://github.com/printu/customerio/releases/tag/3.1.0
