### ISSUE TITLE
Uncaught InvalidArgumentException: App API Key not set! 

### ISSUE THREAD

**Issue by mrzlab630** [printu/customerio#27]
hi
I have a problem with Client.php --> function get()

the function always returns an error: App API Key not set! 

for example:

// Get customer
try {
    $client->customers->get(
        [
            'email' => 'user@example.com',        
        ]
    );
} catch (\GuzzleHttp\Exception\GuzzleException $e) {
    // Handle the error
}

I get an error: App API Key not set! 

but for example:

// Create customer
try {
    $client->customers->add(
        [
            'id' => 1,
            'email' => 'user@example.com',
            'plan' => 'free',
            'created_at' => time()
        ]
    );
} catch (\GuzzleHttp\Exception\GuzzleException $e) {
    // Handle the error
}

great work

**Comment by krzaczek** [comment]
@mrzlab630 customer.io has two seperate API's. They use different credentials. There is an old (API) that uses API Key + side_id

```
$client = new Client('YOUR_API_KEY', 'YOUR_SITE_ID');
```

But there is a newer BETA API that uses Bearer token.

_To authenticate, provide your key as a Bearer token in a HTTP Authorization header. You can create and manage your API keys by visiting your App API Keys page directly or by clicking the Integrations link in the left-hand menu of your Customer.io account and choosing Customer.io API > Manage API Credentials > App API Keys._

You have to provide both to be able to use all endpoints. There is a method `setAppAPIKey($token)` https://github.com/printu/customerio/blob/c8d03e2fa8bcb843451b610b3d1608df88e9eaec/src/Client.php#L91

**Comment by mrzlab630** [comment]
Oh, I'm sorry, I'm stupid. I already saw it myself.

**Comment by krzaczek** [comment]
@mrzlab630 I will add and example and more info in the README

**Comment by mrzlab630** [comment]
great idea.
