### ISSUE TITLE
Support for EU region

### ISSUE THREAD

**Issue by krzaczek** [printu/customerio#36]
https://customer.io/docs/api/?region=eu

**Comment by JulesLagadic** [comment]
Would be great to support the EU Region, as the request fail for EU customers !

**Comment by krzaczek** [comment]
Should be ready next week :)

**Comment by ThorstenPoppe** [comment]
I need this feature too, when will this be available?

**Comment by krzaczek** [comment]
@JulesLagadic @ThorstenPoppe since I don't own any accounts in EU region are You willing to test a pre-release package with EU support enabled ?

**Comment by ThorstenPoppe** [comment]
@krzaczek I tested the pre-release version, it's working with our EU account.
Thank you very much!

**Comment by krzaczek** [comment]
Released in 3.2.0
