### ISSUE TITLE
App API key auth

### ISSUE THREAD

**Issue by imprfekt** [printu/customerio#37]
Hello!
First of all, thank you for this wonderful package! :)

[As of April 14th at 00:00 UTC, Customer.io no longer accepts basic auth for the App API.](https://customer.io/docs/api/#tag/appAuth)
Shouldn't the following method be updated so **both** App API and Beta API use Bearer auth?
https://github.com/printu/customerio/blob/d0664fa42726be4f2d92d72666bdffc31b4ccd41/src/Client.php#L255
_(i.e. add `case self::API_ENDPOINT:` just above `case self::API_ENDPOINT_BETA:`)_ 

Didn't want to open a Pull request before asking, maybe I'm missing something. @krzaczek

**Comment by krzaczek** [comment]
@imprfek I have to check that but yes a simple fix would be to add `API_ENDPOINT` to support Bearer token

**Comment by krzaczek** [comment]
It look sile only the `track` endpoint will support Basic Auth starting from tommorow. It's strange i didn't get the email as we use both api extensively .

**Comment by imprfekt** [comment]
Received this email 13 days ago: https://prnt.sc/11c5y50

**Comment by krzaczek** [comment]
Found the message in a node.js client issue :) https://github.com/customerio/customerio-node/issues/45

**Comment by krzaczek** [comment]
Released as https://github.com/printu/customerio/releases/tag/3.1.1
