### ISSUE TITLE
"Add or update a customer device" is not relevant

### ISSUE THREAD

**Issue by burstmeman** [printu/customerio#42]
Looks like customer.io has updated the endpoint for customer devices. Hence, it needs to be updated to its actual state.

The current version of [the code](https://github.com/printu/customerio/blob/master/src/Endpoint/Customers/Devices.php#L16) requires the following data:
```json
{
  "id": "{ customer_id }",
  "device_id": "{ device_token }",
  "platform": "{ platform_type }"
}
```

According to [the documentation](https://customer.io/docs/api/#operation/add_device), this should require the following data:
```json
{
  "id": "{ customer_id }",
  "device" : {
    "id": "{ device_token }",
    "platform": "{ platform_type }"
  }
}
```

**Comment by krzaczek** [comment]
Released in 3.2.1
