### ISSUE TITLE
Requerid properties when add or update person in custmer.io

### ISSUE THREAD

**Issue by Wlvio** [printu/customerio#47]
Endpoint/Customers.php

    public function add(array $options)
    {
        if (!isset($options['id']) && !isset($options['email'])) {
            $this->mockException('User id or email is required!', 'PUT');
        } // @codeCoverageIgnore

        $path = $this->setCustomerPathWithIdentifier($options);

        return $this->client->put($path, $options);
    }

Change, plz, 
"!isset($options['id']) && !isset($options['email'])"
to
!isset($options['id']) or !isset($options['email'])"

Official documentation https://customer.io/docs/api/#operation/identify
"The unique value representing a person. The values you use to identify a person may be an id, email address, or the cio_id (when updating people), depending on your workspace settings."

**Comment by krzaczek** [comment]
This is not a solution to fix the problem. If You need to update a user by `cio_id` You wll have to wait till this https://github.com/printu/customerio/pull/46 gets merged
