### ISSUE TITLE
Allow to set query parameters for some API methods

### ISSUE THREAD

**Issue by sngrl2** [printu/customerio#52]
For example, I want to search customers by filter, with custom **limit** (up to 1000, not default 50):
https://www.customer.io/docs/api/#operation/getPeopleFilter

In documentation says that I can provide `limit` key at query parameters (in url, not request body) at some POST methods, but I don't see this ability at the package :(

In addition, I cannot use the package's capabilities to use the logic of generating urls for endpoints like a `\Customerio\Endpoint\Base::customerPath` (for example, to make a request on my own) because of them declared as protected or private.

Finally I wrote this snippet as solution:

```
$method = 'customers?' . http_build_query(['limit' => 1000]);
$json = [
    'filter'   => $filter,
    'endpoint' => $client->getRegion()->apiUri(),
];
$response = $client->post($method, $json);
```

But I believe that you can provide ability for more comfortable package usage :pray:

**Comment by krzaczek** [comment]
Hey @sngrl2 

Thx for pointing that out. Will try to make the necessary changes in near future. I'm a little bit busy right now but is seems like an easy task.

Best,
Paweł

**Comment by krzaczek** [comment]
@sngrl2 released as https://github.com/printu/customerio/releases/tag/3.5.0

Just add `query` node to `$options`

```php
$client->customers->search([
        'query' => [
            'limit' => 5,
            'start' => 'MDoyMzg='
        ],
        'filter' => [
            "attribute" => [
               "field" => "email",
                "operator" => "exists"
            ]
        ]
    ]);
```
