### ISSUE TITLE
Make public getters for Client class properties which related to Customer.io endpoints

### ISSUE THREAD

**Issue by sngrl2** [printu/customerio#54]
We are using your package with Laravel framework via [Facades](https://laravel.com/docs/8.x/facades) feature.

It's concept that allow to use regular not static php classes as preconfigured objects with ability to make methods calls chains with first call as for static class, for example: `DB::table('some')->find(1)`

But this feature is allowed only for methods of the class, but not properties. This is make some dificulties, so our current code now is something like that:

```php
$client = CustomerIO::getFacadeRoot();
$client->customers->add([...]);
```

But with public getters eponymous for the endpoint-properties it will be possible to make something like that:

```php
CustomerIO::customers()->add([...]);
```

Full list of the properties, which are need a getter, listed at the constructor:

```php
$this->events = new Endpoint\Events($this);
$this->customers = new Endpoint\Customers($this);
$this->page = new Endpoint\Page($this);
$this->campaigns = new Endpoint\Campaigns($this);
$this->messages = new Endpoint\Messages($this);
$this->messageTemplates = new Endpoint\MessageTemplates($this);
$this->newsletters = new Endpoint\Newsletters($this);
$this->segments = new Endpoint\Segments($this);
$this->exports = new Endpoint\Exports($this);
$this->activities = new Endpoint\Activities($this);
$this->senderIdentities = new Endpoint\SenderIdentities($this);
$this->send = new Endpoint\Send($this);
$this->collection = new Endpoint\Collections($this);
```

**Comment by pkrzaczkowski-hippo** [comment]
@sngrl2 feel free to send a PR

**Comment by sngrl2** [comment]
@pkrzaczkowski-hippo ready!

**Comment by krzaczek** [comment]
@sngrl2 merge into master - i will publish it today

**Comment by krzaczek** [comment]
Released as https://github.com/printu/customerio/releases/tag/3.5.1
